name: Create Repo

on:
  workflow_dispatch:
    inputs:
      initiative-name:
        description: 'Name of the initiative'
        required: true
        default: 'initiative-x'
        type: string

jobs:
    create-repo:
        runs-on: ubuntu-latest
        permissions: 
           # write-all
            # issues: write
            # actions: write
            contents: write
        steps:
            - name: Create with API
              run: |
                  # response=$(
                  curl -L \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{secrets.PAT}}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/pietronromano/arch-community/generate \
                  -d '{"owner":"pietronromano","name":"${{inputs.initiative-name}}","description":"This is your first initiative repository","include_all_branches":false,"private":false}'
                  # )
                  echo "create-repo=$response" >> $GITHUB_OUTPUT
        